# -------- Base image --------
FROM node:18-alpine

# -------- App directory --------
WORKDIR /app

# -------- Install dependencies --------
COPY package*.json ./
RUN npm install --only=production

# -------- Copy source code --------
COPY . .

# -------- Expose port --------
EXPOSE 3000

# -------- Start app --------
CMD ["node", "server.js"]