# -------- Build Stage --------
FROM node:18-slim AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Generate Prisma Client
RUN npx prisma generate

# Build TypeScript
RUN npm run build


# -------- Production Stage --------
FROM node:18-slim

WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl

COPY package*.json ./

# Install only production deps
RUN npm install --only=production

# Copy everything needed
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/src/proto ./src/proto

EXPOSE 5001

CMD ["sh", "-c", "npx prisma migrate deploy && node dist/src/index.js"]